apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-account
  description: App that agglutinates other apps to compose the my account
  tags:
    - typescript
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex-apps/my-account
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: ATMCJN60
    vtex.com/platform-flow-id: Merch#6
    vtex.com/sdd-check-skip: 'true'
    vtex.com/sdd-check-skip-reason: This is a public repository
spec:
  lifecycle: stable
  owner: te-0020
  type: frontend-ui
  dependsOn: []
